### ISSUE TITLE
Package cannot be downloaded through yum repository because of http error 403

### ISSUE THREAD

**Issue by scrool** [alvistack/ansible-role-teamviewer#4]
On Fedora 35 yum repository was successfully added but on `yum install` step it fails with (yaml formatted):

```
  failures:
  - No package teamviewer available.
  item:
    name: teamviewer
    state: latest
  msg: Failed to install some of the specified packages
```
Manual attempt to install (`sudo dnf install teamviewer`) reports:

```
Errors during downloading metadata for repository 'teamviewer':
  - Status code: 403 for https://linux.teamviewer.com/yum/preview/main/binary-x86_64/repodata/repomd.xml (IP: 65.9.96.78)
Error: Failed to download metadata for repo 'teamviewer': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

According to documentation https://community.teamviewer.com/English/kb/articles/30666-update-teamviewer-on-linux-via-repository a yum repository is added after an installation. On a separate machine a teamviewer repo file was created with:

```
baseurl=https://linux.teamviewer.com/yum/stable/main/binary-$basearch/
```

I'm not sure if `preview` might still work but `stable` seem to work now.

**Comment by hswong3i** [comment]
The line from `stable` change into `preview` introduced by https://github.com/alvistack/ansible-role-teamviewer/commit/dd4724a80c82cbd2cdf457de80163913f6ee4bdd, due to https://community.teamviewer.com/English/discussion/122410/teamviewer-support-on-wayland-experimental-state-%F0%9F%A7%AA.

Since I am now using Ubuntu 22.04 Desktop daily with default XWayland, I am looking for `preview` release with incoming connection support. BTW, it looks like teamviewer repo pattern not such predictable.

Anyway, let's rollback it as default `stable` channel, and so we could simply run `teamviewer repo preview` to op-in preview channel manually ;-)
